language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env: MINIMUM_VERSIONS=false

php:
  - 7.1
  - 7.2
  - 7.3


matrix:
  include:
    - php: 7.1
      env: MINIMUM_VERSIONS=true

install:
  - if [[ $MINIMUM_VERSIONS = false ]]; then composer install; fi
  - if [[ $MINIMUM_VERSIONS = true ]]; then composer update --no-interaction --prefer-lowest; fi

script:
  - composer run test
  - composer run check

after_script:
  - if [ -f "build/logs/clover.xml" ]; then vendor/bin/php-coveralls; fi
